#!/usr/bin/env python3

import sys, argparse, json

def parse_args():
  parser = argparse.ArgumentParser(
            prog='incident.io Scheduler',
            description='Creates a schedule based on exceptions')
  parser.add_argument('--schedule')
  parser.add_argument('--overrides')
  parser.add_argument('--fromDate')
  parser.add_argument('--untilDate')
  return parser.parse_args()

def parse_schedule(fname):
  try:
    with open(fname) as f:
      return json.load(f)
  except OSError:
    print("Could not open/read file:", fname)
    sys.exit()

if __name__ == "__main__":
  args = parse_args()
  schedule = parse_schedule(args.schedule)
